SELECT INSCRICAO
      ,ROUND((NOTA_CN + NOTA_CH + NOTA_LC + NOTA_MT + NOTA_REDACAO) / 5.0, 2) 'MEDIA_PARTICIPANTE'
FROM vw_microdados
WHERE ANO = 2020
  AND NOTA_CN IS NOT NULL
  AND NOTA_CH IS NOT NULL
  AND NOTA_LC IS NOT NULL
  AND NOTA_MT IS NOT NULL
  AND NOTA_REDACAO IS NOT NULL
GROUP BY INSCRICAO
ORDER BY MEDIA_PARTICIPANTE DESC
