SELECT ROUND(AVG(NOTA_CN), 2)      'MEDIA_CN'
      ,ROUND(AVG(NOTA_CH), 2)      'MEDIA_CH'
      ,ROUND(AVG(NOTA_LC), 2)      'MEDIA_LC'
      ,ROUND(AVG(NOTA_MT), 2)      'MEDIA_MT'
      ,ROUND(AVG(NOTA_REDACAO), 2) 'MEDIA_REDACAO'
FROM vw_microdados
WHERE ANO = 2020
  AND NOTA_CN IS NOT NULL
  AND NOTA_CH IS NOT NULL
  AND NOTA_LC IS NOT NULL
  AND NOTA_MT IS NOT NULL
  AND NOTA_REDACAO IS NOT NULL