SELECT COD_MUN_ESCOLA
      ,MUN_ESCOLA
      ,UF_ESCOLA
      ,ROUND(AVG((NOTA_CN + NOTA_CH + NOTA_LC + NOTA_MT + NOTA_REDACAO) / 5.0), 2) 'MEDIA_ESCOLA'
FROM vw_microdados
WHERE ANO = 2020
  AND COD_MUN_ESCOLA IS NOT NULL
  AND NOTA_CN IS NOT NULL
  AND NOTA_CH IS NOT NULL
  AND NOTA_LC IS NOT NULL
  AND NOTA_MT IS NOT NULL
  AND NOTA_REDACAO IS NOT NULL
GROUP BY COD_MUN_ESCOLA, MUN_ESCOLA, UF_ESCOLA
ORDER BY MEDIA_ESCOLA DESC
