CREATE TABLE viz_microdados_rj AS
SELECT INSCRICAO
      ,FAIXA_ETARIA
      ,GENERO
      ,COR_RACA
      ,TIPO_ESCOLA
      ,NOTA_CN
      ,NOTA_CH
      ,NOTA_LC
      ,NOTA_MT
      ,STATUS_REDACAO
      ,NOTA_REDACAO
      ,ESCOLARIDADE_PAI
      ,ESCOLARIDADE_MAE
      ,GRUPO_OCUPACAO_PAI
      ,OCUPACAO_PAI
      ,GRUPO_OCUPACAO_MAE
      ,OCUPACAO_MAE
      ,RENDA_FAMILIAR 
      ,COMPUTADOR
      ,INTERNET
FROM vw_microdados 
WHERE UF_PROVA = 'RJ'
  AND NOTA_CN IS NOT NULL 
  AND NOTA_CH IS NOT NULL 
  AND NOTA_LC IS NOT NULL 
  AND NOTA_MT IS NOT NULL 
  AND NOTA_REDACAO IS NOT NULL