CREATE TABLE fato_escola (
    NU_INSCRICAO BIGINT NOT NULL,
    NU_ANO INT NOT NULL,
    CO_MUNICIPIO_ESC INT NOT NULL,
    TP_DEPENDENCIA_ADM_ESC INT,
    TP_LOCALIZACAO_ESC INT,
    TP_SIT_FUNC_ESC INT,
    PRIMARY KEY (NU_INSCRICAO, NU_ANO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO fato_escola 
SELECT
    NU_INSCRICAO,
    NU_ANO,
    CO_MUNICIPIO_ESC,
    TP_DEPENDENCIA_ADM_ESC,
    TP_LOCALIZACAO_ESC,
    TP_SIT_FUNC_ESC
FROM microdados_enem_2020
WHERE NU_INSCRICAO IS NOT NULL
  AND CO_MUNICIPIO_ESC IS NOT NULL;

ALTER TABLE fato_escola
ADD CONSTRAINT fk_mun_escola FOREIGN KEY (CO_MUNICIPIO_ESC)
REFERENCES dim_municipio(CO_MUNICIPIO);

ALTER TABLE fato_escola
ADD CONSTRAINT fk_dep_adm FOREIGN KEY (TP_DEPENDENCIA_ADM_ESC)
REFERENCES dim_dependencia_adm_escola(CO_DEP_ADM);

ALTER TABLE fato_escola
ADD CONSTRAINT fk_local_escola FOREIGN KEY (TP_LOCALIZACAO_ESC)
REFERENCES dim_localizacao_escola(CO_LOCALIZACAO);

ALTER TABLE fato_escola
ADD CONSTRAINT fk_func_escola FOREIGN KEY (TP_SIT_FUNC_ESC)
REFERENCES dim_funcionamento_escola(CO_FUNCIONAMENTO);