CREATE TABLE fato_redacao (
    NU_INSCRICAO BIGINT NOT NULL,         
    NU_ANO INT NOT NULL,                  
    TP_STATUS_REDACAO INT NOT NULL,
    NU_NOTA_COMP1 DOUBLE, 
    NU_NOTA_COMP2 DOUBLE,
    NU_NOTA_COMP3 DOUBLE,
    NU_NOTA_COMP4 DOUBLE,
    NU_NOTA_COMP5 DOUBLE,
    NU_NOTA_REDACAO DOUBLE,
    PRIMARY KEY (NU_INSCRICAO, NU_ANO)
);
INSERT INTO fato_redacao
SELECT NU_INSCRICAO
      ,NU_ANO
      ,TP_STATUS_REDACAO
      ,NU_NOTA_COMP1
      ,NU_NOTA_COMP2
      ,NU_NOTA_COMP3
      ,NU_NOTA_COMP4
      ,NU_NOTA_COMP5
      ,NU_NOTA_REDACAO
FROM microdados_enem_2020
WHERE NU_INSCRICAO IS NOT NULL
  AND NU_ANO IS NOT NULL
  AND TP_STATUS_REDACAO IS NOT NULL

ALTER TABLE fato_redacao
ADD CONSTRAINT fk_status FOREIGN KEY (TP_STATUS_REDACAO)
REFERENCES dim_status_redacao(CO_STATUS);
