CREATE TABLE fato_local_prova (
    NU_INSCRICAO BIGINT NOT NULL,
    NU_ANO INT NOT NULL,
    CO_MUNICIPIO_PROVA INT NOT NULL,
    PRIMARY KEY (NU_INSCRICAO, NU_ANO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO fato_local_prova
SELECT NU_INSCRICAO
      ,NU_ANO
      ,CO_MUNICIPIO_PROVA 
FROM microdados_enem_2020
WHERE NU_INSCRICAO IS NOT NULL
  AND NU_ANO IS NOT NULL
  AND CO_MUNICIPIO_PROVA IS NOT NULL

ALTER TABLE fato_local_prova
ADD CONSTRAINT fk_mun_prova FOREIGN KEY (CO_MUNICIPIO_PROVA)
REFERENCES dim_municipio(CO_MUNICIPIO);