CREATE TABLE fato_participante (
    NU_INSCRICAO BIGINT NOT NULL,
    NU_ANO INT NOT NULL,
    TP_FAIXA_ETARIA INT,
    TP_SEXO CHAR(1),
    TP_ESTADO_CIVIL INT,
    TP_COR_RACA INT,
    TP_NACIONALIDADE INT,
    TP_ST_CONCLUSAO INT,
    TP_ANO_CONCLUIU INT,
    TP_ESCOLA INT,
    TP_ENSINO INT,
    IN_TREINEIRO INT,
    PRIMARY KEY (NU_INSCRICAO, NU_ANO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO fato_participante
SELECT NU_INSCRICAO
      ,NU_ANO
      ,TP_FAIXA_ETARIA
      ,TP_SEXO
      ,TP_ESTADO_CIVIL
      ,TP_COR_RACA
      ,TP_NACIONALIDADE
      ,TP_ST_CONCLUSAO
      ,TP_ANO_CONCLUIU
      ,TP_ESCOLA
      ,TP_ENSINO
      ,IN_TREINEIRO
FROM microdados_enem_2020
WHERE NU_INSCRICAO IS NOT NULL
  AND NU_ANO IS NOT NULL;

ALTER TABLE fato_participante
ADD CONSTRAINT fk_faixa_etaria FOREIGN KEY (TP_FAIXA_ETARIA)
REFERENCES dim_faixa_etaria(CO_FAIXA_ETARIA)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_estado_civil FOREIGN KEY (TP_ESTADO_CIVIL)
REFERENCES dim_estado_civil(CO_ESTADO_CIVIL)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_cor_raca FOREIGN KEY (TP_COR_RACA)
REFERENCES dim_cor_raca(CO_COR_RACA)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_nacionalidade FOREIGN KEY (TP_NACIONALIDADE)
REFERENCES dim_nacionalidade(CO_NACIONALIDADE)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_st_conclusao FOREIGN KEY (TP_ST_CONCLUSAO)
REFERENCES dim_situacao_conclusao(CO_CONCLUSAO)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_ano_conclusao FOREIGN KEY (TP_ANO_CONCLUIU)
REFERENCES dim_ano_conclusao(CO_ANO_CONCLUSAO)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_tipo_escola FOREIGN KEY (TP_ESCOLA)
REFERENCES dim_tipo_escola(CO_TIPO_ESCOLA)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_tipo_ensino FOREIGN KEY (TP_ENSINO)
REFERENCES dim_tipo_ensino(CO_TIPO_ENSINO)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_treineiro FOREIGN KEY (IN_TREINEIRO)
REFERENCES dim_sim_ou_nao(CO_ZERO_UM)

ALTER TABLE fato_participante
ADD CONSTRAINT fk_sexo FOREIGN KEY (TP_SEXO)
REFERENCES dim_sexo(CO_SEXO)