CREATE TABLE dim_localizacao_escola (
    CO_LOCALIZACAO int NOT NULL,
    DESC_LOCALIZACAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (CO_LOCALIZACAO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO dim_localizacao_escola (CO_LOCALIZACAO, DESC_LOCALIZACAO)
VALUES
    (1, 'Urbana'),
    (2, 'Rural');