CREATE TABLE dim_municipio (
    CO_MUNICIPIO int NOT NULL,
    NO_MUNICIPIO VARCHAR(50) NOT NULL,
    CO_UF int NOT NULL,
    PRIMARY KEY (CO_MUNICIPIO),
    CONSTRAINT fk_municipio FOREIGN KEY (CO_UF)
      REFERENCES dim_uf(CO_UF)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO dim_municipio (CO_MUNICIPIO, NO_MUNICIPIO, CO_UF)
SELECT DISTINCT CO_MUNICIPIO_PROVA
      ,NO_MUNICIPIO_PROVA
      ,CO_UF_PROVA
FROM microdados_enem_2020
WHERE CO_MUNICIPIO_PROVA IS NOT NULL

UNION

SELECT DISTINCT CO_MUNICIPIO_ESC
      ,NO_MUNICIPIO_ESC
      ,CO_UF_ESC
FROM microdados_enem_2020
WHERE CO_MUNICIPIO_ESC IS NOT NULL
  AND CO_MUNICIPIO_ESC NOT IN (
      SELECT DISTINCT CO_MUNICIPIO_PROVA
      FROM microdados_enem_2020
      WHERE CO_MUNICIPIO_PROVA IS NOT NULL
  );