CREATE TABLE dim_uf (
    CO_UF int NOT NULL,
    SG_UF CHAR(2) NOT NULL,
    PRIMARY KEY (CO_UF)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO dim_uf (CO_UF, SG_UF)
SELECT DISTINCT CO_UF_PROVA
      ,SG_UF_PROVA
FROM microdados_enem_2020
WHERE CO_UF_PROVA IS NOT NULL

UNION

SELECT DISTINCT CO_UF_ESC
      ,SG_UF_ESC
FROM microdados_enem_2020
WHERE CO_UF_ESC IS NOT NULL
  AND CO_UF_ESC NOT IN (
      SELECT DISTINCT CO_UF_PROVA
      FROM microdados_enem_2020
      WHERE CO_UF_PROVA IS NOT NULL
  );